[meta]
save_dir = "exp"
seed = 3407

[finetune]
finetune = false

[trainer]
path = "trainer_single_opt.Trainer"
[trainer.args]
max_epochs = 100
gradient_percentile = 90
gradient_history_size = 1000
save_max_score = false
save_ckpt_interval = 1
max_patience = 10
max_num_checkpoints = 100
gradient_accumulation_steps = 1
validation_interval = 1
freeze_wavlm = false
lr_decay = false
use_one_cycle_lr = false

[optimizer]
path = "torch.optim.AdamW"
[optimizer.args]
lr = 1e-3

[model]
path = "diarizen.models.eend.model_fbank_conformer.Model"
[model.args]
n_fft = 400
n_mels = 80
win_length = 25 # ms
hop_length = 10 # ms
sample_rate = 16000
attention_in = 256
ffn_hidden = 1024
num_head = 4
num_layer = 4
dropout = 0.1
chunk_size = 8
use_posi = false
output_activate_function = false
selected_channel = 0

[train_dataset]
path = "dataset.DiarizationDataset"
[train_dataset.args]
scp_file = "data/AMI_AliMeeting_AISHELL4/train/wav.scp"
rttm_file = "data/AMI_AliMeeting_AISHELL4/train/rttm"
uem_file = "data/AMI_AliMeeting_AISHELL4/train/all.uem"
chunk_size = 8
chunk_shift = 6
sample_rate = 16000

[train_dataset.dataloader]
batch_size = 16
num_workers = 1
drop_last = true
pin_memory = true

[validate_dataset]
path = "dataset.DiarizationDataset"
[validate_dataset.args]
scp_file = "data/AMI_AliMeeting_AISHELL4/dev/wav.scp"
rttm_file = "data/AMI_AliMeeting_AISHELL4/dev/rttm"
uem_file = "data/AMI_AliMeeting_AISHELL4/dev/all.uem"
chunk_size = 8
chunk_shift = 8
sample_rate = 16000

[validate_dataset.dataloader]
batch_size = 16
num_workers = 1
drop_last = true
pin_memory = true

